name: swagger_parser_pages
description: Web interface for swagger_parser
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.1.0

dependencies:
  archive: ^3.3.7
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  swagger_parser:
    path:
      ../swagger_parser
  url_launcher: ^6.1.12

dev_dependencies:
  carapacik_lints: ^1.5.1

flutter:
  uses-material-design: true
