name: swagger_parser
description: Package that generates REST clients and data classes from OpenApi definition file
version: 1.11.3
repository: https://github.com/Carapacik/swagger_parser/tree/main/swagger_parser
homepage: https://omega-r.com
topics:
  - swagger
  - openapi
  - codegen
  - api
  - json
environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.0
  collection: ^1.17.1
  path: ^1.8.3
  yaml: ^3.1.1

dev_dependencies:
  carapacik_lints: ^1.4.2
  test: ^1.24.4
