name: swagger_parser
description: Package that generates REST clients and data classes from OpenApi definition file
version: 1.18.0
repository: https://github.com/Carapacik/swagger_parser/tree/main/swagger_parser
homepage: https://omega-r.com
topics:
  - swagger
  - openapi
  - codegen
  - api
  - rest
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  args: ^2.5.0
  collection: ^1.18.0
  meta: ^1.10.0
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  carapacik_lints: ^1.6.0
  test: ^1.24.9
