name: swagger_parser
description: Package that generates REST clients and data classes from OpenApi definition file
version: 0.6.1
repository: https://github.com/Carapacik/swagger_parser
homepage: https://omega-r.com
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.3.1
  collection: ^1.16.0
  path: ^1.8.2
  yaml: ^3.1.1

dev_dependencies:
  carapacik_lints: ^1.1.6
  test: ^1.21.4
