name: swagger_parser
description: Package that generates REST clients and data classes from OpenApi definition file
version: 1.3.5
repository: https://github.com/Carapacik/swagger_parser/tree/main/swagger_parser
homepage: https://omega-r.com
topics:
  - swagger
  - openapi
  - codegen
  - api
  - json
environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  args: ^2.3.1
  collection: ^1.17.0
  path: ^1.8.2
  yaml: ^3.1.1

dev_dependencies:
  carapacik_lints: ^1.3.2
  test: ^1.22.0
